#!/bin/bash

set -e

function usage_and_exit {
    echo "usage: condor-incsub [-n] f1 f2 ..."
    echo "  -n MAXJOBS  Maximum number of jobs in queue, default 9000"
    exit 1
}

maxjobs=9000

while getopts "n:" Option
do
    case $Option in
        n) maxjobs=$OPTARG ;;
        [?]) usage_and_exit ;;
    esac
done
shift $((OPTIND - 1))

nfiles=$#
if [[ $nfiles -lt 1 ]]; then
    usage_and_exit
fi

index=1
for file; do

    subf="${file}.submitted"

    if [[ ! -e ${subf} ]]; then
        while true; do
            njobs=$(condor_q | grep "Total for $USER" | awk '{print $4}')
            if ((njobs < maxjobs)); then

                echo "found ${njobs} $(date)"
                echo "submitting ${file} ${index}/${nfiles}"

                dname=$(dirname "${file}")
                bname=$(basename "${file}")

                pushd "${dname}" > /dev/null
                condor_submit "${bname}"
                popd > /dev/null

                touch "${file}.submitted"

                break
            fi
            sleep 30
        done
    else
        echo "skipping previously submitted: ${file} ${index}/${nfiles}"
    fi

    ((index += 1))
done
