#!/bin/bash

odir=~/www/condorq
file="$odir/condorq.txt"

mkdir -p $odir


tmpfile="$odir/condorq-tmp.txt"
sleep 1
while [ 1 ]; do

    condorq > $tmpfile

    mv -f $tmpfile $file

    sleep 300
done
