#!/bin/bash
#
# usage: setup-astro [options] start|stop|restart
#
# start: Set up the connection.  If the connection exists the request is 
#        ignored.
# stop:  Disconnect. If the connection does not exist the request is ignored.
# restart: run "stop" then "start".
#
# by default the caller's username is used for connection.  To over-ride
# this use the -u option
#   setup-astro -u username start

gateway=rssh01
domain=rhic.bnl.gov
fullhost=$gateway.$domain

function usage
{
    echo "
usage: 
    setup-astro [options] start|stop|restart

    By default, the caller's username is used for logging into the remote host.
    send -u <username> to use an alternative username
"
}
function connect
{
	check=$(ps auxww | grep "ssh.*nx" | grep -v grep)
	if [ "$check" == "" ]; then
		echo "Connecting to $gateway"
        #ssh -f -N -l ${username} ${fullhost}
        ssh -f -N -L 7825:nx01.rcf.bnl.gov:22 -l ${username} ${fullhost}
	fi

}

function disconnect
{
	check=$(ps auxww | grep "ssh.*nx" | grep -v grep)
    while [[ $check != "" ]]; do
	    #if [ "$check" != "" ]; then
		id=$(echo $check | awk '{print $2}')
		echo "disconnecting from $gateway (jobid $id)"
		kill $id
	    check=$(ps auxww | grep "*ssh.*nx" | grep -v grep)
    done

}

username=$(whoami)
while getopts "u:" Option
  do
  case $Option in
      u) username=$OPTARG ;;
      [?]) usage
           exit 45 ;;  
  esac
done
shift $(($OPTIND - 1))

if [ $# -lt 1 ]; then
    usage
	exit 45
fi

action=$1

if [ "$action" == "start" ]; then
	connect
elif [ "$action" == "stop" ]; then
	disconnect
elif [ "$action" == "restart" ]; then
	disconnect
	connect
else
	echo "Unrecognized action: $action"
	exit 45
fi


