#!/bin/bash

#mrxvt -e vim -c "set filetype=mail" -c "set spell spelllang=en_us" $1 &

gtkfile=~/.themes/Clearlooks-DarkOrange/gtk-2.0/gtkrc
if [[ -e $gtkfile ]]; then
    GTK2_RC_FILES=$gtkfile gvim -c "set filetype=mail" -c "set spell spelllang=en_us" -c "colorscheme zenburn" $1 &
else
    gvim -c "set filetype=mail" -c "set spell spelllang=en_us" -c "colorscheme zenburn" $1 &
fi
