#!/bin/bash

# the xfce4 power manager won't lock the screen on
# suspend when using xscreensaver, so we need to
# use slock
#
# for this to work you need to install
# - xserver-xorg-input-synaptics (for synclient)
# - xss-lock
# - slock

# this is not getting killed off on logout, and
# each time lxdm comes up it starts a new one

killall gnome-keyring-daemon
killall dwm-status-bar

if [ -r ~/.Xdefaults ]; then
	xrdb -merge ~/.Xdefaults
fi

if [ -r ~/.Xmodmap ]; then
	xmodmap ~/.Xmodmap
fi

# turn off the touch pad
if [ -x /usr/bin/synclient ]; then
    synclient TouchPadOff=1
fi

# speed up the keyboard
xset r rate 300 30

# sleeptime=1

# blank screen after 10 minutes
# xss-lock also locks the screen when suspended, which
# if [ -x /usr/bin/xss-lock ]; then
#     if [ -x /usr/bin/slock ]; then
#         # this seems to be over ridden when it is longer than
#         # the setting in the xfce4 power management
#         xset s 600
#         /usr/bin/xss-lock slock &
#     fi
# fi

if [ -x /usr/bin/nm-applet ]; then
    nm-applet --sm-disable &	
fi

if [ -x /usr/bin/xfce4-power-manager ]; then
    xfce4-power-manager &
fi

track_id=$(xinput | grep Track | awk '{print $6}' | cut -d = -f 2)
xinput --set-prop ${track_id} 'libinput Accel Profile Enabled' 0, 1

touch_id=$(xinput | grep -i Touchscreen | awk '{print $5}' | cut -d = -f 2)
xinput disable $touch_id

~/shell_scripts/dwm-status-bar &

xsetroot -solid black
# xsetroot -solid '#FCE1C5'

if [[ -e ~/.fehbg ]]; then
    bash ~/.fehbg &
fi

# sleep $sleeptime

exec dwm
